Using STDERR vs. STDOUT

diff --git a/build_zip b/build_zip
--- a/build_zip
+++ b/build_zip
@@ -17,5 +17,5 @@ if [ "$NAME" != "" -a ! -e "$NAME" ] ; then
 	# remove the temporary directory
 	rm -R ./${NAME}/
 else
-	echo "Error: the temporary directory we want to create already exists."
+	>&2 echo "Error: the temporary directory we want to create already exists."
 fi
